spring:
  devtools:
    livereload:
      enabled : true
  datasource:
    url: jdbc:h2:C:/ljw-study/codesoom/demotask
    username: sa
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: 12345678901234567890123456789012


